version: 2
jobs:
  build_and_test:
    docker:
      - image: /Users/khoanguyen/workspace/workspace/demo_first/php/Dockerfile
    steps:
      - checkout
      - run: cp demo_repository/.env.example demo_repository/.env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:  composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # run test
      - run: phpcs --standard=Framgia app
